// This file was automatically generated by ts_bind, do not modify it manually
import type { MouseReport } from "./MouseReport";
import type { SlimKeyReport } from "./SlimKeyReport";
import type { Tone } from "./Tone";

export const Action = {
  keyAction: 0x01,
  mouseAction: 0x02,
  summerAction: 0x03,
};

export type Action = 
| { type: 0x01, data: SlimKeyReport }
| { type: 0x02, data: MouseReport }
| { type: 0x03, data: Tone }