// This file was automatically generated by ts_bind, do not modify it manually

export const Command = {
  changeConfig: 0x01,
  getConfig: 0x02,
  flash: 0x03,
  summ: 0x04,
};

export type Command = typeof Command[keyof typeof Command];