// This file was automatically generated by ts_bind, do not modify it manually

import type { KnobAction } from "./KnobAction";
import type { KeyAction } from "./KeyAction";
import type { Effect } from "./Effect";

export interface Config {
   keyAction: [(KeyAction)[], (KeyAction)[], (KeyAction)[], (KeyAction)[], (KeyAction)[], (KeyAction)[]];
   knobAction: KnobAction;
   inputDelay: number;
   effect: Effect;
}