// This file was automatically generated by ts_bind, do not modify it manually

const webUrl: string = "macro.sillycode.tech";
const manufacturer: string = "SillGoose123 & Leo";
const product: string = "MacroBoard";
const serialNumber: string = "v1";
const usbVid: number = 0x1209;
const usb_pid: number = 0x0001;
const usbPid: number = 0x0001;