// This file was automatically generated by ts_bind, do not modify it manually

export const numLeds: number = 5;
export const manufacturer: string = "SillGoose123 & Leo";
export const product: string = "MacroBoard";
export const serialNumber: string = "v1";
export const usbVid: number = 0x1209;
export const usbPid: number = 0x0512;
export const webUrl: string = "http://localhost:5173/";