// This file was automatically generated by ts_bind, do not modify it manually

import type { RGB8 } from "./RGB8";

export interface Effect {
   colors: (RGB8)[];
   timeDiff: number;
   ticks: number;
}