// This file was automatically generated by ts_bind, do not modify it manually

import type { RotaryAction } from "./RotaryAction";
import type { Action } from "./Action";

export interface KnobAction {
   rotaryAction: RotaryAction;
   switch: (Action)[];
}