// This file was automatically generated by ts_bind, do not modify it manually

import type { Action } from "./Action";
import type { RotaryAction } from "./RotaryAction";


export interface KnobAction {
   rotaryAction: RotaryAction;
   switch: (Action)[];
}