// This file was automatically generated by ts_bind, do not modify it manually

export const Tone = {
  low: 0x01,
  medium: 0x02,
  default: 0x04,
  high: 0x03,
};

export type Tone = typeof Tone[keyof typeof Tone];